### PR TITLE
stock prediction model added

### PR DESCRIPTION
**Pull request by Anushreebasics**

### CODE REVIEW

**Comment by aditi1042003** [comment]
@Anushreebasics  please create pull request after being assigned the issue  from next .

add a readme file specifying your approach and model , dataset used

**Comment by Anushreebasics** [comment]
okay I will take care from next time

**Review by Nitya-Pasrija — CHANGES_REQUESTED** [review]
Please add a readme file specifying your approach, model and dataset used here

**Comment by Anushreebasics** [comment]
@Nitya-Pasrija  I have added the readme.

**Review by Nitya-Pasrija — APPROVED** [review]

**Pull request merged**
